name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        jit: [1205, 1254, 0]
        os: [ubuntu-20.04, windows-2019]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: 8.0.3
          ini-values: opcache.enable_cli=1, opcache.jit=${{ matrix.jit }}, opcache.jit_buffer_size=8M
          extensions: :xdebug

      - name: Run test scripts
        run: php run-tests.php
